import type { CreateServerOptions, McpSurfaceFacetMap } from '@ontrails/mcp';

export const trailsMcpIncludedTrails = [
  'adapter.check',
  'add.surface',
  'add.trail',
  'compile',
  'create',
  'create.adapter',
  'deprecate',
  'dev.clean',
  'dev.reset',
  'dev.stats',
  'doctor',
  'draft.promote',
  'guide',
  'regrade',
  'release.check',
  'release.smoke',
  'revise',
  'run',
  'run.example',
  'run.examples',
  'survey',
  'survey.brief',
  'survey.diff',
  'survey.resource',
  'survey.signal',
  'survey.surfaces',
  'survey.trail',
  'topo',
  'topo.history',
  'topo.pin',
  'topo.unpin',
  'validate',
  'warden',
  'warden.guide',
  'wayfind.adapters',
  'wayfind.contract',
  'wayfind.diff',
  'wayfind.errors',
  'wayfind.examples',
  'wayfind.impact',
  'wayfind.nearby',
  'wayfind.overview',
  'wayfind.search',
  'wayfind.trails',
] as const;

export const trailsMcpFacets = {
  inspect: {
    description:
      'Inspect saved topo structure, resources, signals, surfaces, and diffs.',
    mcp: { loading: 'deferred' },
    trails: [
      'survey',
      'topo',
      'guide',
      'survey.brief',
      'survey.diff',
      'survey.resource',
      'survey.signal',
      'survey.surfaces',
      'survey.trail',
      'topo.history',
    ],
  },
} satisfies McpSurfaceFacetMap;

export const trailsMcpSurfaceOptions = {
  description:
    'Trails framework operator surface. Use MCP resources for cold context, direct tools for high-signal work, and the inspect facet for saved topo reads.',
  facets: trailsMcpFacets,
  include: trailsMcpIncludedTrails,
  mcpResources: { examples: true, graph: true, surfaceMap: true },
  name: 'trails',
} satisfies CreateServerOptions;
